#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto post generator for esportsai.io
Designed safe for GitHub Actions and Jekyll builds.
"""

import os
import datetime
import random

SITE_DOMAIN = os.environ.get("SITE_DOMAIN", "").strip() or os.path.basename(os.getcwd())

DOMAINS = [
    'esportsai.io', 'botgame.io', 'metaversebot.io', 'nftgameai.com',
    'hubgaming.io', 'botdefi.io', 'nftgamepro.com', 'botesports.com',
    'aiesports.io', 'pronftgame.com', 'botplay.io', 'botweb3ai.com',
    'botblockchain.io'
]

IMAGES = {
    'esportsai.io': [
        "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=1200&h=630&fit=crop",
        "https://source.unsplash.com/1200x630/?esports,gaming",
        "https://picsum.photos/1200/630?random=7312"
    ],
    'default': [
        "https://source.unsplash.com/1200x630/?gaming,competition",
        "https://picsum.photos/1200/630?random=5555"
    ]
}

TOPICS = [
    "Latency Optimization for Pro-level Play",
    "AI-assisted Strategy: Live Tactical Hints",
    "Scouting Opponents with Automated Metrics",
    "Reducing Input Lag: Tips for Competitive Players",
    "Modeling Player Behavior for Better Drafts",
    "Edge Inference for Low-latency Assistants"
]


def pick_image(domain):
    pool = IMAGES.get(domain, IMAGES['default'])
    return random.choice(pool)


def pick_backlinks(domain):
    others = [d for d in DOMAINS if d != domain]
    random.shuffle(others)
    picked = others[:6]
    return "\n".join([f"- [{d}](https://{d})" for d in picked])


def generate_md(domain):
    today = datetime.date.today().isoformat()
    title = random.choice(TOPICS)
    image = pick_image(domain)
    desc = title + " — quick esports AI insight"
    backlinks_md = pick_backlinks(domain)

    template = """---
layout: post
title: "__TITLE__"
date: __DATE__
author: "EsportsAI Team"
description: "__DESC__"
image: "__IMAGE__"
---

_This insight was auto-generated by EsportsAI._

<!-- featured image -->
{% if page.image %}
<img src="{{ page.image }}" alt="{{ page.title }}" class="hero-img">
{% endif %}

<!-- ad -->
{% include ad.html %}

__INTRO__

__BODY__

---

## Key Insights
- Measure latency and variance, not only averages.
- Instrument your stack for reproducible tests.
- Use small ensembles for live decision smoothing.

## Friendly Network
__BACKLINKS__

{% include analytics.html %}
"""

    intro = "Quick take: micro-optimizations and instrumentation win close matches."
    # build body with slight variability to avoid identical posts
    body_parts = [
        "High-frequency telemetry matters: capture packet times and render events.",
        "Small measurement biases compound over many rounds—calibrate often.",
        "Use rolling windows and percentile metrics to detect regressions early."
    ]
    # shuffle small
    random.shuffle(body_parts)
    body = "\n\n".join(body_parts)

    md = template.replace("__TITLE__", title)\
                 .replace("__DATE__", today)\
                 .replace("__DESC__", desc)\
                 .replace("__IMAGE__", image)\
                 .replace("__INTRO__", intro)\
                 .replace("__BODY__", body)\
                 .replace("__BACKLINKS__", backlinks_md)

    # slugify
    slug = title.lower().replace(" ", "-").replace("/", "-")
    slug = "".join([c for c in slug if c.isalnum() or c in "-"]).strip("-")
    path = f"_posts/{today}-{slug}.md"
    return path, md


def main():
    os.makedirs("_posts", exist_ok=True)
    fn, content = generate_md(SITE_DOMAIN)
    with open(fn, "w", encoding="utf-8") as f:
        f.write(content)
    print("WROTE:", fn)


if __name__ == "__main__":
    main()
